steps:
- name: gcr.io/cloud-builders/docker
  args: [build, '-t', 'us-west1-docker.pkg.dev/${PROJECT_ID}/master-build/build:latest', '.']
images:
- 'us-west1-docker.pkg.dev/${PROJECT_ID}'
options:
  logging: CLOUD_LOGGING_ONLY