steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [build, '-t', 'us-west1-docker.pkg.dev/${PROJECT_ID}/artifact-registry-test-02-docker/base-beam-image:latest', './flextemplate/beam-worker']
images: 
- 'us-west1-docker.pkg.dev/${PROJECT_ID}/artifact-registry-test-02-docker/base-beam-image:latest'
timeout: 36000s
options:
  logging: CLOUD_LOGGING_ONLY

    
